package com.sentry.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.*;
import java.time.LocalDateTime;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class FriendRequest {
    /*
     * Id of the friend request.
     * Generated by the database.
     * Read-only.
     */
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private Long id;

    /*
     * User ID of the sender.
     */
    private Long senderId;

    /*
     * User ID of the receiver.
     */
    private Long receiverId;

    /*
     * Status of the friend request (pending, accepted, declined, or cancelled).
     */
    private String status;

    /*
     * Date and time of creation.
     */
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private LocalDateTime createdAt;

    /*
     * Date and time of last update.
     */
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private LocalDateTime updatedAt;

    // Related user profiles populated for frontend representation
    private User sender;
    private User receiver;
}
