package com.sentry.friend;

import com.sentry.user.User;
import com.sentry.user.UserRepository;
import com.sentry.user.UserRepositoryImpl;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

@JdbcTest
@Import({FriendshipRepositoryImpl.class, UserRepositoryImpl.class})
public class FriendshipRepositoryTest {

    @Autowired
    private FriendshipRepository friendshipRepository;

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    private User alice;
    private User bob;
    private User charlie;

    @BeforeEach
    public void setUp() {
        // Create users table
        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS users (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "username VARCHAR(32) NOT NULL UNIQUE, " +
                "display_name VARCHAR(50) NOT NULL, " +
                "password_hash VARCHAR(255) NOT NULL, " +
                "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP" +
                ")");

        // Create friendships table with constraint
        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS friendships (" +
                "user_id_1 BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE, " +
                "user_id_2 BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE, " +
                "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, " +
                "PRIMARY KEY (user_id_1, user_id_2), " +
                "CONSTRAINT check_user_order CHECK(user_id_1 < user_id_2)" +
                ")");

        jdbcTemplate.execute("DELETE FROM friendships");
        jdbcTemplate.execute("DELETE FROM users");

        // Insert test users
        alice = userRepository.save(User.builder().username("alice").displayName("Alice").passwordHash("pwd").build());
        bob = userRepository.save(User.builder().username("bob").displayName("Bob").passwordHash("pwd").build());
        charlie = userRepository.save(User.builder().username("charlie").displayName("Charlie").passwordHash("pwd").build());
    }

    @Test
    public void testSaveAndExists() {
        Friendship f = Friendship.builder()
                .userId1(alice.getId())
                .userId2(bob.getId())
                .build();

        Friendship saved = friendshipRepository.save(f);
        assertNotNull(saved);
        // Assert canonical ordering userId1 < userId2
        long expectedMin = Math.min(alice.getId(), bob.getId());
        long expectedMax = Math.max(alice.getId(), bob.getId());
        assertEquals(expectedMin, saved.getUserId1());
        assertEquals(expectedMax, saved.getUserId2());
        assertNotNull(saved.getCreatedAt());

        // Check exists
        assertTrue(friendshipRepository.exists(alice.getId(), bob.getId()));
        assertTrue(friendshipRepository.exists(bob.getId(), alice.getId()));
    }

    @Test
    public void testFindFriendsByUserId() {
        Friendship f1 = Friendship.builder().userId1(alice.getId()).userId2(bob.getId()).build();
        Friendship f2 = Friendship.builder().userId1(alice.getId()).userId2(charlie.getId()).build();
        friendshipRepository.save(f1);
        friendshipRepository.save(f2);

        List<User> aliceFriends = friendshipRepository.findFriendsByUserId(alice.getId());
        assertEquals(2, aliceFriends.size());
        assertTrue(aliceFriends.stream().anyMatch(u -> u.getUsername().equals("bob")));
        assertTrue(aliceFriends.stream().anyMatch(u -> u.getUsername().equals("charlie")));

        List<User> bobFriends = friendshipRepository.findFriendsByUserId(bob.getId());
        assertEquals(1, bobFriends.size());
        assertEquals("alice", bobFriends.get(0).getUsername());
    }

    @Test
    public void testDelete() {
        Friendship f = Friendship.builder().userId1(alice.getId()).userId2(bob.getId()).build();
        friendshipRepository.save(f);

        assertTrue(friendshipRepository.exists(alice.getId(), bob.getId()));
        friendshipRepository.delete(alice.getId(), bob.getId());
        assertFalse(friendshipRepository.exists(alice.getId(), bob.getId()));
    }
}
