package com.sentry.friend;

import com.sentry.user.User;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;

import java.sql.PreparedStatement;
import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;

@JdbcTest
@Import(FriendRequestRepositoryImpl.class)
public class FriendRequestRepositoryTest {

    @Autowired
    private FriendRequestRepository friendRequestRepository;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    private User alice;
    private User bob;
    private User charlie;

    private User insertUser(String username, String displayName) {
        KeyHolder keyHolder = new GeneratedKeyHolder();
        jdbcTemplate.update(connection -> {
            PreparedStatement ps = connection.prepareStatement(
                    "INSERT INTO users (username, display_name, password_hash) VALUES (?, ?, ?)",
                    new String[]{"id"}
            );
            ps.setString(1, username);
            ps.setString(2, displayName);
            ps.setString(3, "hash");
            return ps;
        }, keyHolder);
        return User.builder()
                .id(keyHolder.getKey().longValue())
                .username(username)
                .displayName(displayName)
                .passwordHash("hash")
                .build();
    }

    @BeforeEach
    public void setUp() {
        // Create users table
        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS users (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "username VARCHAR(32) NOT NULL UNIQUE, " +
                "display_name VARCHAR(50) NOT NULL, " +
                "password_hash VARCHAR(255) NOT NULL, " +
                "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP" +
                ")");

        // Create friend_requests table
        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS friend_requests (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "sender_id BIGINT NOT NULL, " +
                "receiver_id BIGINT NOT NULL, " +
                "status VARCHAR(20) NOT NULL, " +
                "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, " +
                "updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, " +
                "CONSTRAINT unique_sender_receiver UNIQUE(sender_id, receiver_id), " +
                "CONSTRAINT check_sender_receiver_different CHECK(sender_id <> receiver_id), " +
                "FOREIGN KEY (sender_id) REFERENCES users(id) ON DELETE CASCADE, " +
                "FOREIGN KEY (receiver_id) REFERENCES users(id) ON DELETE CASCADE" +
                ")");

        // Clear tables
        jdbcTemplate.execute("DELETE FROM friend_requests");
        jdbcTemplate.execute("DELETE FROM users");

        // Seed users to satisfy foreign key constraints
        alice = insertUser("alice", "Alice");
        bob = insertUser("bob", "Bob");
        charlie = insertUser("charlie", "Charlie");
    }

    @Test
    public void testSave_Insert() {
        FriendRequest request = FriendRequest.builder()
                .senderId(alice.getId())
                .receiverId(bob.getId())
                .status("pending")
                .build();

        FriendRequest saved = friendRequestRepository.save(request);
        assertNotNull(saved);
        assertNotNull(saved.getId());
        assertEquals("pending", saved.getStatus());
        assertEquals(alice.getId(), saved.getSenderId());
        assertEquals(bob.getId(), saved.getReceiverId());
    }

    @Test
    public void testSave_Update() {
        FriendRequest request = FriendRequest.builder()
                .senderId(alice.getId())
                .receiverId(bob.getId())
                .status("pending")
                .build();

        FriendRequest saved = friendRequestRepository.save(request);
        saved.setStatus("accepted");

        FriendRequest updated = friendRequestRepository.save(saved);
        assertEquals("accepted", updated.getStatus());
        assertEquals(saved.getId(), updated.getId());
    }

    @Test
    public void testFindById_Success() {
        FriendRequest request = FriendRequest.builder()
                .senderId(alice.getId())
                .receiverId(bob.getId())
                .status("pending")
                .build();
        FriendRequest saved = friendRequestRepository.save(request);

        Optional<FriendRequest> found = friendRequestRepository.findById(saved.getId());
        assertTrue(found.isPresent());
        assertEquals(saved.getId(), found.get().getId());
        assertEquals("pending", found.get().getStatus());

        // Verify joined sender and receiver User structures are populated
        assertNotNull(found.get().getSender());
        assertEquals("alice", found.get().getSender().getUsername());
        assertNotNull(found.get().getReceiver());
        assertEquals("bob", found.get().getReceiver().getUsername());
    }

    @Test
    public void testFindById_NotFound() {
        Optional<FriendRequest> found = friendRequestRepository.findById(999L);
        assertFalse(found.isPresent());
    }

    @Test
    public void testFindBySenderAndReceiver() {
        FriendRequest request = FriendRequest.builder()
                .senderId(alice.getId())
                .receiverId(bob.getId())
                .status("pending")
                .build();
        friendRequestRepository.save(request);

        // Find by exact direction
        Optional<FriendRequest> found1 = friendRequestRepository.findBySenderAndReceiver(alice.getId(), bob.getId());
        assertTrue(found1.isPresent());

        // Find by opposite direction (should still match because findBySenderAndReceiver checks both directions)
        Optional<FriendRequest> found2 = friendRequestRepository.findBySenderAndReceiver(bob.getId(), alice.getId());
        assertTrue(found2.isPresent());
        assertEquals(found1.get().getId(), found2.get().getId());

        // Find nonexistent pair
        Optional<FriendRequest> notFound = friendRequestRepository.findBySenderAndReceiver(alice.getId(), charlie.getId());
        assertFalse(notFound.isPresent());
    }

    @Test
    public void testFindPendingByUserId() {
        // Alice -> Bob (Pending)
        friendRequestRepository.save(FriendRequest.builder()
                .senderId(alice.getId())
                .receiverId(bob.getId())
                .status("pending")
                .build());

        // Charlie -> Alice (Pending)
        friendRequestRepository.save(FriendRequest.builder()
                .senderId(charlie.getId())
                .receiverId(alice.getId())
                .status("pending")
                .build());

        // Bob -> Charlie (Accepted) - Should not be returned
        friendRequestRepository.save(FriendRequest.builder()
                .senderId(bob.getId())
                .receiverId(charlie.getId())
                .status("accepted")
                .build());

        List<FriendRequest> alicePending = friendRequestRepository.findPendingByUserId(alice.getId());
        assertEquals(2, alicePending.size());

        List<FriendRequest> charliePending = friendRequestRepository.findPendingByUserId(charlie.getId());
        assertEquals(1, charliePending.size());
    }

    @Test
    public void testDeleteById() {
        FriendRequest request = FriendRequest.builder()
                .senderId(alice.getId())
                .receiverId(bob.getId())
                .status("pending")
                .build();
        FriendRequest saved = friendRequestRepository.save(request);

        friendRequestRepository.deleteById(saved.getId());

        Optional<FriendRequest> found = friendRequestRepository.findById(saved.getId());
        assertFalse(found.isPresent());
    }

    @Test
    public void testDeleteBySenderIdAndReceiverId() {
        FriendRequest request = FriendRequest.builder()
                .senderId(alice.getId())
                .receiverId(bob.getId())
                .status("pending")
                .build();
        FriendRequest saved = friendRequestRepository.save(request);

        assertTrue(friendRequestRepository.findById(saved.getId()).isPresent());
        friendRequestRepository.deleteBySenderIdAndReceiverId(alice.getId(), bob.getId());
        assertFalse(friendRequestRepository.findById(saved.getId()).isPresent());
    }
}
