package com.sentry.repository;

import com.sentry.model.User;
import com.sentry.repository.repositoryimpl.UserRepositoryImpl;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;

import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;

@JdbcTest
@Import(UserRepositoryImpl.class)
public class UserRepositoryTest {

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @BeforeEach
    public void setUp() {
        // Create the users table in the H2 in-memory database
        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS users (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "username VARCHAR(32) NOT NULL UNIQUE, " +
                "display_name VARCHAR(50) NOT NULL, " +
                "password_hash VARCHAR(255) NOT NULL, " +
                "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP" +
                ")");
        jdbcTemplate.execute("DELETE FROM users");
    }

    @Test
    public void testSave_Insert() {
        User user = User.builder()
                .username("dbuser")
                .displayName("DB User")
                .passwordHash("pwd")
                .build();

        User saved = userRepository.save(user);
        assertNotNull(saved);
        assertNotNull(saved.getId());
        assertTrue(saved.getId() > 0);
        assertEquals("dbuser", saved.getUsername());
        
        // Verify in DB
        Optional<User> found = userRepository.findById(saved.getId());
        assertTrue(found.isPresent());
        assertEquals("dbuser", found.get().getUsername());
        assertNotNull(found.get().getCreatedAt());
    }

    @Test
    public void testSave_Update() {
        User user = User.builder()
                .username("dbuser")
                .displayName("DB User")
                .passwordHash("pwd")
                .build();
        User saved = userRepository.save(user);

        saved.setDisplayName("Updated Name");
        User updated = userRepository.save(saved);

        assertEquals("Updated Name", updated.getDisplayName());
        
        Optional<User> found = userRepository.findById(saved.getId());
        assertTrue(found.isPresent());
        assertEquals("Updated Name", found.get().getDisplayName());
    }

    @Test
    public void testFindById_NotFound() {
        Optional<User> found = userRepository.findById(999L);
        assertFalse(found.isPresent());
    }

    @Test
    public void testFindByUsername() {
        User user = User.builder()
                .username("findme")
                .displayName("Find")
                .passwordHash("pwd")
                .build();
        userRepository.save(user);

        Optional<User> found = userRepository.findByUsername("findme");
        assertTrue(found.isPresent());
        assertEquals("findme", found.get().getUsername());

        Optional<User> notFound = userRepository.findByUsername("nonexistent");
        assertFalse(notFound.isPresent());
    }

    @Test
    public void testFindAll() {
        User u1 = User.builder().username("u1").displayName("User 1").passwordHash("pwd").build();
        User u2 = User.builder().username("u2").displayName("User 2").passwordHash("pwd").build();
        userRepository.save(u1);
        userRepository.save(u2);

        List<User> all = userRepository.findAll();
        assertEquals(2, all.size());
    }

    @Test
    public void testDeleteById() {
        User user = User.builder()
                .username("delete")
                .displayName("Delete")
                .passwordHash("pwd")
                .build();
        User saved = userRepository.save(user);

        userRepository.deleteById(saved.getId());

        Optional<User> found = userRepository.findById(saved.getId());
        assertFalse(found.isPresent());
    }

    @Test
    public void testExistsByUsername() {
        User user = User.builder()
                .username("exists")
                .displayName("Exists")
                .passwordHash("pwd")
                .build();
        userRepository.save(user);

        assertTrue(userRepository.existsByUsername("exists"));
        assertFalse(userRepository.existsByUsername("doesnotexist"));
    }
}
